# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# specifies that push to master branch cause a continuous integration build to run
trigger:
- master

strategy:
  matrix:
    win-chrome:
      imageName: windows-2019
      browser: chrome

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  appname: 'SpaceGameWeb'
  installDir: c://

steps:


- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# - task: PythonScript@0
#   inputs:
#     scriptSource: inline
#     script: |
#       import sys
#       print ('Executing script file is:', str(sys.argv[0]))
#       print ('The arguments are:', str(sys.argv))

# - pwsh: |
#    echo "##vso[task.prependpath]$env:CHROMEWEBDRIVER"
#   displayName: Adds ChromeWebDriver for Selenium to PATH 

# - script: webdrivermanager chrome --linkpath AUTO
#   displayName: Adds ChromeWebDriver for Selenium to PATH 

- task: UseDotNet@2
  displayName: 'Use .NET Core 3.1 sdk'
  inputs:
    packageType: sdk
    version: '3.1.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: Build DotNet Application
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release'

# - task: DotNetCoreCLI@2
#   displayName: Run DotNet Application
#   inputs:
#     command: run
#     projects: '**/*.csproj'
#     arguments: '--configuration Release --no-build --project Tailspin.SpaceGame.Web' # Update this to match your need

- task: PythonScript@0
  displayName: 'Test Space Game Web'
  inputs:
    scriptSource: 'filePath'
    scriptPath: main.py