# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# specifies that push to master branch cause a continuous integration build to run
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  appname: 'SpaceGame Web'
  installDir: c://

steps:

# acquires a specific version of .NET Core (3.1)
- task: UseDotNet@2
  displayName: 'Use .NET Core 3.1 sdk'
  inputs:
    packageType: sdk
    version: '3.1.x'
    installationPath: $(installDir)/dotnet


- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build for $(appname) $(buildConfiguration)'


# - script: dotnet build --configuration $(buildConfiguration) --no-build --project Tailspin.SpaceGame.
#   displayName: 'dotnet build for $(appname) $(buildConfiguration)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: PythonScript@0
  displayName: 'Test Space Game Web'
  inputs:
    scriptSource: 'filePath' # Options: filePath, inline
    scriptPath: main.py